apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml

commonLabels:
  app: quorum
  managed-by: kustomize

namespace: quorum

configMapGenerator:
  - name: quorum-config
    literals:
      - NODE_ENV=production
      - PORT=3000
      - ENABLE_SWAGGER=true
      - ENABLE_METRICS=true

secretGenerator:
  - name: quorum-secrets
    envs:
      - secrets.env
