apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: quorum-dev

namePrefix: dev-

replicas:
  - name: quorum-api
    count: 1
  - name: quorum-worker
    count: 1

configMapGenerator:
  - name: quorum-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - ENABLE_SWAGGER=true
      - LOG_LEVEL=debug

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
    target:
      kind: Deployment
      name: .*-api
